# Generated by Django 3.2.5 on 2021-08-16 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0017_alter_country_country_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='app_store',
        ),
        migrations.RemoveField(
            model_name='country',
            name='google_play',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='app_store',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='country',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='google_play',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_review_id', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('app_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscribe.appstore')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscribe.country')),
                ('google_play', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscribe.googleplay')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribe.subscriber')),
            ],
        ),
    ]
